<?php

declare(strict_types=1);

namespace App\Core;

use App\Config\Database as DatabaseConfig;
use PDO;
use PDOException;
use PDOStatement;
use RuntimeException;
use Throwable;

/**
 * PDO wrapper: one lazily created connection plus a few small helpers so that
 * models never talk to PDO directly and every query uses prepared statements.
 *
 *   $rows = Database::select('SELECT * FROM users WHERE role = ?', ['admin']);
 *
 * There is no query builder and no ORM.
 */
final class Database
{
    private static ?PDO $connection = null;

    private function __construct()
    {
    }

    /**
     * Shared PDO connection (created on first use).
     *
     * @throws RuntimeException When the database cannot be reached.
     */
    public static function connection(): PDO
    {
        if (self::$connection instanceof PDO) {
            return self::$connection;
        }

        try {
            self::$connection = new PDO(
                DatabaseConfig::dsn(),
                DatabaseConfig::username(),
                DatabaseConfig::password(),
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::ATTR_STRINGIFY_FETCHES => false,
                ]
            );
        } catch (PDOException $exception) {
            // Server side note only; the client never sees this detail.
            Logger::error('Database connection failed', [
                'host' => DatabaseConfig::host(),
                'database' => DatabaseConfig::name(),
                'error' => $exception->getMessage(),
            ]);

            throw new RuntimeException('Database connection failed', 0, $exception);
        }

        return self::$connection;
    }

    /**
     * Run a prepared SELECT and return all rows.
     *
     * @param array<int|string, mixed> $params
     * @return array<int, array<string, mixed>>
     */
    public static function select(string $sql, array $params = []): array
    {
        return self::run($sql, $params)->fetchAll();
    }

    /**
     * Run a prepared SELECT and return the first row (or null).
     *
     * @param array<int|string, mixed> $params
     * @return array<string, mixed>|null
     */
    public static function selectOne(string $sql, array $params = []): ?array
    {
        $row = self::run($sql, $params)->fetch();

        return $row === false ? null : $row;
    }

    /**
     * Run a prepared INSERT/UPDATE/DELETE and return the affected row count.
     *
     * @param array<int|string, mixed> $params
     */
    public static function execute(string $sql, array $params = []): int
    {
        return self::run($sql, $params)->rowCount();
    }

    /**
     * Id generated by the last INSERT.
     */
    public static function lastInsertId(): int
    {
        return (int) self::connection()->lastInsertId();
    }

    /**
     * Run a callback inside a transaction; rolled back on any exception.
     *
     * @param callable(PDO): mixed $callback
     */
    public static function transaction(callable $callback): mixed
    {
        $pdo = self::connection();
        $pdo->beginTransaction();

        try {
            $result = $callback($pdo);
            $pdo->commit();

            return $result;
        } catch (Throwable $exception) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }

            throw $exception;
        }
    }

    /**
     * @param array<int|string, mixed> $params
     */
    private static function run(string $sql, array $params): PDOStatement
    {
        $statement = self::connection()->prepare($sql);
        $statement->execute($params);

        return $statement;
    }
}